version: "3.8"
services:

  lbfe:
    build:
      context: lbfe
    restart: always

  fe01:
    image: nginx:stable
    ports: 
      - 10001:10001
    volumes:
      - ./fe01:/etc/nginx/templates

  fe02: 
    image: nginx:stable
    ports: 
      - 10002:10002
    volumes:
      - ./fe02:/etc/nginx/templates

