version: "3.8"
services:
  lb_fe:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./lbfe/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fe01
      - fe02
    

  fe01:
    image: httpd:latest
    container_name: fe01
    ports: 
      - "10001:80"
    volumes:
      - ./fe01:/usr/local/apache2/htdocs

  fe02:
    image: httpd:latest
    container_name: fe02
    ports: 
      - "10002:80"
    volumes:
      - ./fe02:/usr/local/apache2/htdocs
