version: "3.8"
services:

  nginxfe:
    image: nginx:stable
    ports: 
      - 80:80
    restart: always

  fe01:
    image: nginx:stable
    ports: 
      - 10001:10001
    volumes:
      - ./fe01:/var/www/html

  fe02: 
    image: nginx:stable
    ports: 
      - 10002:10002
    volumes:
      - ./fe02:/var/www/html

