version: "3.8"
services:

  fe01:
    image: httpd:latest
    container_name: fe01
    ports: 
      - "80:80"
    volumes:
      - ./fe01:/usr/local/apache2/htdocs

  fe02:
    image: httpd:latest
    container_name: fe02
    ports: 
      - "80:81"
    volumes:
      - ./fe02:/usr/local/apache2/htdocs
