version: "3.8"
services:
  lb_fe:
    image: nginx:latest
    ports:
      - "80:80"
    build: ./lbfe
    

  fe01:
    image: httpd:latest
    container_name: fe01
    ports: 
      - "10001:80"
    volumes:
      - ./fe01:/usr/local/apache2/htdocs

  fe02:
    image: httpd:latest
    container_name: fe02
    ports: 
      - "10002:80"
    volumes:
      - ./fe02:/usr/local/apache2/htdocs
