version: '3.9'
services:
  lbfe:
    container_name: lbfe
    build: ./lbfe
    ports:
      - "80:80"
    depends_on:
      - fe01
      - fe02

  fe01:
    container_name: fe01
    build: ./fe01
    ports: 
      - "10001:80"

  fe02:
    container_name: fe02
    build: ./fe02
    ports: 
      - "10002:80"

  lbbe:
    container_name: lbbe
    build: ./lbfe
    depends_on:
      - media01
      - media02
    ports: 
      - "8008:8008"

  media01:
    container_name: media01
    build: ./media01
    ports: 
      - "10011:80"

  media02:
    container_name: media02
    build: ./media02
    ports: 
      - "10012:80"


