version: '3.9'
services:
  lbfe:
    #image: nginx:latest
    ports:
      - "80:80"
    build: ./lbfe
    depends_on:
      - fe01
      - fe02
    

  fe01:
    #image: httpd:latest
    container_name: fe01
    ports: 
      - "10001:80"
    build: ./fe01

  fe02:
    #image: httpd:latest
    container_name: fe02
    ports: 
      - "10002:80"
    build: ./fe02

  lbbe:
    #image: nginx:latest
    #ports:
    #  - "3000:3000"
    build: ./lbfe
    depends_on:
      - media01
      - media02

  media01:
    #image: httpd:latest
    container_name: media01
    ports: 
      - "10011:3000"
    build: ./media01

  media02:
    #image: httpd:latest
    container_name: media02
    ports: 
      - "10012:3000"
    build: ./media02
