version: '3.9'
services:
  lbfe:
    #image: nginx:latest
    build: ./lbfe
    depends_on:
      - fe01
      - fe02
    networks:
      front:
        ipv4_address: 10.0.1.2

    lbfe02:
      build: ./lbfe
      depends_on:
        - fe01
        - fe02
      ports:
        - "80:80"

  fe01:
    #image: httpd:latest
    container_name: fe01
    #ports: 
    #  - "10001:80"
    build: ./fe01
    networks:
      front:
        ipv4_address: 10.0.1.3

  fe02:
    #image: httpd:latest
    container_name: fe02
    #ports: 
    #  - "10002:80"
    build: ./fe02
    networks:
      front:
        ipv4_address: 10.0.1.4

  lbbe:
    #image: nginx:latest
    #ports:
    #  - "3000:3000"
    build: ./lbfe
    depends_on:
      - media01
      - media02

    networks:
      back:
        ipv4_address: 10.0.2.2

  media01:
    #image: httpd:latest
    container_name: media01
    #ports: 
    #  - "10011:10011"
    build: ./media01
    networks:
      back:
        ipv4_address: 10.0.2.3

  media02:
    #image: httpd:latest
    container_name: media02
    #ports: 
    #  - "10012:10011"
    build: ./media02
    networks:
      back:
        ipv4_address: 10.0.2.4

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.0.2.0/24 
          gateway: 10.0.2.1

